app/blueprints/main/models.py
from app import db, login_manager
from flask_login import UserMixin
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(50), unique=True)
    username = db.Column(db.String(50))
    password = db.Column(db.String(200))
    first_name = db.Column(db.String(50))
    last_name = db.Column(db.String(50))

    def hash_my_password(self, password):
        self.password = generate_password_hash(password)
    
    def check_my_password(self, password):
        return check_password_hash(self.password, password)

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(250))
    body = db.Column(db.String(1200))
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    date_created = db.Column(db.DateTime, default=datetime.utcnow)

class Car(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    make = db.Column(db.String(100))
    model = db.Column(db.String(100))
    year = db.Column(db.Integer)
    color = db.Column(db.String(100))
    price = db.Column(db.Float)
    date_created = db.Column(db.DateTime, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

app/blueprints/api/__init__.py
from flask import Blueprint

bp = Blueprint('api', __name__, url_prefix='/api')

from . import models

app/blueprints/api/routes.py
from . import bp as app
from flask import render_template

app/blueprints/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__, url_prefix="/")

from . import models, routes

app/blueprints/main/routes.py
from . import bp as app
from flask import render_template, request, redirect, url_for, flash
from app.blueprints.main.models import User, Post, Car
from app import db
from flask_login import current_user, login_required

# Routes that return/display HTML

@app.route('/')
@login_required
def home():
    cars = Car.query.all()

    return render_template('home.html', user=current_user, cars=cars)

@app.route('/about')
@login_required
def about():
    return render_template('about.html')

@app.route('/blog')
@login_required
def blog():
    return render_template('blog.html')

@app.route('/post', methods=['POST'])
@login_required
def create_post():
    post_make = request.form['make']
    post_model = request.form['model']
    post_year = request.form['year']
    post_color = request.form['color']
    post_price = request.form['price']
    
    new_car = Car(make=post_make, model=post_model, year=post_year, color=post_color, price=post_price, user_id=current_user.id)

    db.session.add(new_car)
    db.session.commit()

    flash('Post added successfully', 'success')
    return redirect(url_for('main.home'))

@app.route('/post/<id>')
def car(id):
    single_post = Car.query.get(id)
    return render_template('single-post.html', car=single_post)

app/templates/__init__.py
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

db = SQLAlchemy()
migrate = Migrate()
login_manager = LoginManager()

app = Flask(__name__)
# Connecting our config class and our flask application
app.config.from_object(Config)

db.init_app(app)
migrate.init_app(app, db)
login_manager.init_app(app)

from app.blueprints.main import bp as main_bp
app.register_blueprint(main_bp)

from app.blueprints.api import bp as api_bp
app.register_blueprint(api_bp)

from app.blueprints.auth import bp as auth_bp
app.register_blueprint(auth_bp)

app/templates/about.html
{% extends './partials/layout.html' %}

{% block content %}
<h1>About</h1>
<p>Welcome to CarList</p>
{% endblock content %}

app/templates/blog.html
{% extends './partials/layout.html' %}

{% block content %}
<h1>Blog</h1>
<p>These is a blog!</p>
{% endblock content %}

app/templates/home.html
{% extends './partials/layout.html' %}

{% block content %}
<h1>Home</h1>
<p>Welcome {{ user['first_name'] }} {{ user['last_name'] }}.</p>

<h2>Create Post</h2>
<form action="{{ url_for('main.create_post') }}" method="POST" class="my-2">
  <div class="form-group">
    <label for="title">Maker</label>
    <input type="text" class="form-control" id="make" name="make">
  </div>
  <div class="form-group">
    <label for="body">Model</label>
    <input type="text" class="form-control" id="model" name="model">
  </div>
  <div class="form-group">
    <label for="body">Year</label>
    <input type="text" class="form-control" id="year" name="year">
  </div>
  <div class="form-group">
    <label for="body">Color</label>
    <input type="text" class="form-control" id="color" name="color">
  </div>
  <div class="form-group">
    <label for="body">Price</label>
    <input type="text" class="form-control" id="price" name="price">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% for car in cars %}
<div class="card mb-2">
  <div class="card-header">
    <a href="{{ url_for('main.car', id=car['id']) }}">{{ car['make'] }} {{ car['model'] }} ${{ car['price'] }}</a>
  </div>
</div>
{% endfor %}
{% endblock content %}

app/templates/login.html
{% extends './partials/layout.html' %}

{% block content %}
<h1>Login</h1>
<form action="{{ url_for('auth.login') }}" method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class="form-control", placeholder = "Enter your Email") }}
        </fieldset>

    </div>
    <div class="form-group">
        <fieldset id="password-field">
            {{ form.password.label }}
            {{ form.password(class="form-control", placeholder = "Enter your Password") }}
        </fieldset>

    </div>
    <p><small>Don't have an account? <a href="{{ url_for('auth.register') }}">Register here.</a></small></p>
    {{ form.submit_button(class = "btn btn-primary btn-block") }}
</form>
{% endblock content %}

app/templates/partials/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
        integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
</head>

<body>
    <header class="mb-5">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{{ url_for('main.home') }}">CarList</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{{ url_for('main.home') }}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.blog') }}">Blog</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    {% if not current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>

    <main class="container">
        {% with messages = get_flashed_messages(with_categories=True) %}
            {% if messages %}
                {% for category, message in messages %}
                <div class="alert alert-{{ category }}" role="alert">
                    {{ message }}
                </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        <!-- THIS IS WHERE WE WILL PUT EACH PAGE'S CONTENT -->
        {% block content %}{% endblock content %}
    </main>

    <!-- <footer>
        This is a footer
    </footer> -->
</body>

</html>

app/templates/register.html
{% extends './partials/layout.html' %}

{% block content %}
<h1>Register</h1>
<form action="{{ url_for('auth.register') }}" method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class="form-control", placeholder = "Enter your Email here") }}
        </fieldset>

        <!-- <label for="inputEmail">Email address</label>
        <input type="email" class="form-control" id="inputEmail" name="inputEmail" aria-describedby="emailHelp"> -->
        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>
    <div class="form-group">
        <fieldset id="username-field">
            {{ form.username.label }}
            {{ form.username(class="form-control", placeholder = "Enter your Username") }}
        </fieldset>

        <!-- <label for="inputUsername">Username</label>
        <input type="text" class="form-control" id="inputUsername" name="inputUsername"> -->
    </div>
    <div class="form-group">
        <fieldset id="first_name-field">
            {{ form.first_name.label }}
            {{ form.first_name(class="form-control", placeholder = "Enter your First Name") }}
        </fieldset>

        <!-- <label for="inputFirstName">First Name</label>
        <input type="text" class="form-control" id="inputFirstName" name="inputFirstName"> -->
    </div>
    <div class="form-group">
        <fieldset id="last_name-field">
            {{ form.last_name.label }}
            {{ form.last_name(class="form-control", placeholder = "Enter your Last Name") }}
        </fieldset>

        <!-- <label for="inputLastName">Last Name</label>
        <input type="text" class="form-control" id="inputLastName" name="inputLastName"> -->
    </div>
    <div class="form-group">
        <fieldset id="password-field">
            {{ form.password.label }}
            {{ form.password(class="form-control", placeholder = "Enter your Password") }}
        </fieldset>

        <!-- <label for="inputPassword">Password</label>
        <input type="password" class="form-control" id="inputPassword" name="inputPassword"> -->
    </div>
    <div class="form-group">

        <fieldset id="confirm_password-field">
            {{ form.confirm_password.label }}
            {{ form.confirm_password(class="form-control", placeholder = "Confirm your Password") }}
        </fieldset>

        <!-- <label for="inputPasswordConfirm">Confirm Password</label>
        <input type="password" class="form-control" id="inputPasswordConfirm" name="inputPasswordConfirm"> -->
    </div>
    <p><small>Already have an account? <a href="{{ url_for('auth.login') }}">Login here.</a></small></p>
    {{ form.submit_button(class = "btn btn-primary btn-block") }}
</form>
{% endblock content %}

app/templates/single-post.html
{% extends './partials/layout.html' %}

{% block content %}
<div class="card">
    <div class="card-header">
        Car: {{ car['id'] }}
    </div>
    <div class="card-header">
        Maker: {{ car['make'] }}
    </div>
    <div class="card-body">
        Model: {{ car['model'] }}
    </div>    
    <div class="card-body">
        Year: {{ car['year'] }}
    </div>    
    <div class="card-body">
        Color: {{ car['color'] }}
    </div>    
    <div class="card-body">
        Body: {{ car['price'] }}
    </div>    
</div>
{% endblock content %}